global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Pertamina.Common.Exceptions;
global using Pertamina.Common.Validators;
global using Pertamina.Extensions.DisplayText;
global using Pertamina.Extensions.DisplayText.Statics;
global using Pertamina.Extensions.Text;
global using Pertamina.Services.Authorization.Attributes;
global using Pertamina.Services.DateAndTime;
global using SolutionTemplate2.BackEnd.Domain.Entities;
global using SolutionTemplate2.BackEnd.Logics.Common.Extensions;
global using SolutionTemplate2.BackEnd.Services.Database;
global using SolutionTemplate2.Shared.Enums;
global using ApiCallsDisplayTextFor = SolutionTemplate2.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = SolutionTemplate2.Shared.Statics.Audits.DisplayTextFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using ConfigurationsDisplayTextFor = SolutionTemplate2.Shared.Statics.Configurations.DisplayTextFor;
global using CountriesDisplayTextFor = SolutionTemplate2.Shared.Statics.Countries.DisplayTextFor;
global using DocumentsDisplayTextFor = SolutionTemplate2.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsValueFor = SolutionTemplate2.Shared.Statics.Documents.ValueFor;
global using UsersDisplayTextFor = SolutionTemplate2.Shared.Statics.Users.DisplayTextFor;
