global using Microsoft.AspNetCore.Builder;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Pertamina.Common.Exceptions;
global using Pertamina.Services.Database.Common.Extensions;
global using Pertamina.Services.Database.Common.Statics;
global using SolutionTemplate2.BackEnd.Domain.Entities;
global using SolutionTemplate2.BackEnd.Infrastructure.Database.InitialData;
global using SolutionTemplate2.BackEnd.Services.Database;
global using ApiCallsMaximumLengthFor = SolutionTemplate2.Shared.Statics.ApiCalls.MaximumLengthFor;
global using AuditsMaximumLengthFor = SolutionTemplate2.Shared.Statics.Audits.MaximumLengthFor;
global using CommonMaximumLengthFor = Pertamina.Common.Statics.MaximumLengthFor;
global using ConfigurationsMaximumLengthFor = SolutionTemplate2.Shared.Statics.Configurations.MaximumLengthFor;
global using CountriesMaximumLengthFor = SolutionTemplate2.Shared.Statics.Countries.MaximumLengthFor;
global using DocumentsMaximumLengthFor = SolutionTemplate2.Shared.Statics.Documents.MaximumLengthFor;
global using PublicHolidaysMaximumLengthFor = SolutionTemplate2.Shared.Statics.PublicHolidays.MaximumLengthFor;
global using UsersMaximumLengthFor = SolutionTemplate2.Shared.Statics.Users.MaximumLengthFor;
