export const CommonDisplayTextFor = {
  Name: "Name",
  Code: "Code",
  Action: "Action",
  Add: "Add",
  Edit: "Edit",
  Delete: "Delete",
  Details: "Details",
  Cancel: "Cancel",
  Save: "Save",
  Search: "Search",
  Home: "Home",
  Status: "Status",
  No: "No",
  Login: "Login",
  Logout: "Logout",
  Return: "Return",
  Submit: "Submit",
  Update: "Update",
  Publish: "Publish",
  History: "History",
  Verify: "Verify",
  Complete: "Complete",
  Download: "Download",
  File: "File",
  Note: "Note",
  Notes: "Notes",
  Description: "Description",
  Created: "Created",
  CreatedBy: "Created By",
  Modified: "Modified",
  ModifiedBy: "Modified By",
  Loading: "Loading",
  Access: "Access",
  Verified: "Verified",
  NotVerified: "Not Verified",
  Success: "Success",
  Failed: "Failed",
  All: "All",
  New: "New",
  Send: "Send",
  VerificationCode: "Verification Code",
  Email: "Email",
  Password: "Password",
  Welcome: "Welcome",
  About: "About",
  MySession: "My Session",
  MyProfile: "My Profile",
  AccessDenied: "Access Denied",
  NotFound: "Not Found",
  Error: "Error",
  Internal: "Internal",
  External: "External",
  Required: "Required",
  SortNo: "Sort No",
  Key: "Key",
  Value: "Value",
  Subject: "Subject",
  To: "To",
  Cc: "Cc",
  Content: "Content",
  Module: "Module",
  Provider: "Provider",
  Close: "Close",
  Confirm: "Confirm",
  Yes: "Yes",
  NoLabel: "No",
} as const;
