global using FluentValidation;
global using Pertamina.Common.Dto.Requests;
global using Pertamina.Common.Dto.Responses;
global using Pertamina.Common.Validators;
global using Pertamina.Common.Validators.Extensions;
global using ApiCallsDisplayTextFor = SolutionTemplate2.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = SolutionTemplate2.Shared.Statics.Audits.DisplayTextFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using CommonMaximumLengthFor = Pertamina.Common.Statics.MaximumLengthFor;
global using CommonMinimumLengthFor = Pertamina.Common.Statics.MinimumLengthFor;
global using ConfigurationsDisplayTextFor = SolutionTemplate2.Shared.Statics.Configurations.DisplayTextFor;
global using ConfigurationsMaximumLengthFor = SolutionTemplate2.Shared.Statics.Configurations.MaximumLengthFor;
global using ConfigurationsMinimumLengthFor = SolutionTemplate2.Shared.Statics.Configurations.MinimumLengthFor;
global using CountriesDisplayTextFor = SolutionTemplate2.Shared.Statics.Countries.DisplayTextFor;
global using CountriesMaximumLengthFor = SolutionTemplate2.Shared.Statics.Countries.MaximumLengthFor;
global using CountriesMinimumLengthFor = SolutionTemplate2.Shared.Statics.Countries.MinimumLengthFor;
global using DocumentsDisplayTextFor = SolutionTemplate2.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsMaximumLengthFor = SolutionTemplate2.Shared.Statics.Documents.MaximumLengthFor;
global using DocumentsMinimumLengthFor = SolutionTemplate2.Shared.Statics.Documents.MinimumLengthFor;
global using PublicHolidaysDisplayTextFor = SolutionTemplate2.Shared.Statics.PublicHolidays.DisplayTextFor;
global using PublicHolidaysMinimumValueFor = SolutionTemplate2.Shared.Statics.PublicHolidays.MinimumValueFor;
global using UsersDisplayTextFor = SolutionTemplate2.Shared.Statics.Users.DisplayTextFor;
global using UsersMaximumLengthFor = SolutionTemplate2.Shared.Statics.Users.MaximumLengthFor;
global using UsersMinimumLengthFor = SolutionTemplate2.Shared.Statics.Users.MinimumLengthFor;
