global using FluentValidation;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.Extensions.Options;
global using MudBlazor;
global using Pertamina.Common.Exceptions;
global using Pertamina.Common.Validators;
global using Pertamina.Extensions.DisplayText;
global using Pertamina.Extensions.DisplayText.Statics;
global using Pertamina.Extensions.Identity;
global using Pertamina.Extensions.Size;
global using SolutionTemplate2.FrontEnd.Infrastructure.AppConfigFrontEnd;
global using SolutionTemplate2.FrontEnd.Services.AppConfigFrontEnd;
global using SolutionTemplate2.FrontEnd.WebUi.Common.Extensions;
global using SolutionTemplate2.FrontEnd.WebUi.Common.Statics;
global using SolutionTemplate2.Shared.Enums;
global using AdministrationApiCallsBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Features.ApiCalls.Statics.BreadcrumbFor;
global using AdministrationApiCallsRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Features.ApiCalls.Statics.RouteFor;
global using AdministrationAuditsBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Features.Audits.Statics.BreadcrumbFor;
global using AdministrationAuditsRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Features.Audits.Statics.RouteFor;
global using AdministrationBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Statics.BreadcrumbFor;
global using AdministrationConfigurationsBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Features.Configurations.Statics.BreadcrumbFor;
global using AdministrationConfigurationsRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Features.Configurations.Statics.RouteFor;
global using AdministrationDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Statics.DisplayTextFor;
global using AdministrationPermissions = SolutionTemplate2.Shared.Dto.Modules.Administration.Permissions;
global using AdministrationRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Administration.Statics.RouteFor;
global using ApiCallsDisplayTextFor = SolutionTemplate2.Shared.Statics.ApiCalls.DisplayTextFor;
global using AuditsDisplayTextFor = SolutionTemplate2.Shared.Statics.Audits.DisplayTextFor;
global using AuthenticationRouteFor = SolutionTemplate2.FrontEnd.Infrastructure.Authentication.Statics.RouteFor;
global using CommonBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Common.Statics.BreadcrumbFor;
global using CommonDefaultValueFor = Pertamina.Common.Statics.DefaultValueFor;
global using CommonDisplayTextFor = Pertamina.Common.Statics.DisplayTextFor;
global using ConfigurationsDisplayTextFor = SolutionTemplate2.Shared.Statics.Configurations.DisplayTextFor;
global using CountriesDisplayTextFor = SolutionTemplate2.Shared.Statics.Countries.DisplayTextFor;
global using DocumentsDisplayTextFor = SolutionTemplate2.Shared.Statics.Documents.DisplayTextFor;
global using DocumentsMaximumValueFor = SolutionTemplate2.Shared.Statics.Documents.MaximumValueFor;
global using ExamplesBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Statics.BreadcrumbFor;
global using ExamplesDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Statics.DisplayTextFor;
global using ExamplesDocumentsBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Documents.Statics.BreadcrumbFor;
global using ExamplesDocumentsRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Documents.Statics.RouteFor;
global using ExamplesDummiesDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Dummies.Statics.DisplayTextFor;
global using ExamplesDummiesRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Dummies.Statics.RouteFor;
global using ExamplesEmailsBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Emails.Statics.BreadcrumbFor;
global using ExamplesEmailsDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Emails.Statics.DisplayTextFor;
global using ExamplesEmailsRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Emails.Statics.RouteFor;
global using ExamplesLoadingsBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Loadings.Statics.BreadcrumbFor;
global using ExamplesLoadingsDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Loadings.Statics.DisplayTextFor;
global using ExamplesLoadingsRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.Loadings.Statics.RouteFor;
global using ExamplesPublicHolidaysBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.PublicHolidays.Statics.BreadcrumbFor;
global using ExamplesPublicHolidaysRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Features.PublicHolidays.Statics.RouteFor;
global using ExamplesRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Examples.Statics.RouteFor;
global using MainBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Main.Statics.BreadcrumbFor;
global using MainDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Main.Statics.DisplayTextFor;
global using MainMyProfileRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Main.Features.MyProfile.Statics.RouteFor;
global using MainPermissions = SolutionTemplate2.Shared.Dto.Modules.Main.Permissions;
global using MainRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.Main.Statics.RouteFor;
global using MasterDataBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.MasterData.Statics.BreadcrumbFor;
global using MasterDataCountriesBreadcrumbFor = SolutionTemplate2.FrontEnd.WebUi.Modules.MasterData.Features.Countries.Statics.BreadcrumbFor;
global using MasterDataCountriesRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.MasterData.Features.Countries.Statics.RouteFor;
global using MasterDataDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Modules.MasterData.Statics.DisplayTextFor;
global using MasterDataPermissions = SolutionTemplate2.Shared.Dto.Modules.MasterData.Permissions;
global using MasterDataRouteFor = SolutionTemplate2.FrontEnd.WebUi.Modules.MasterData.Statics.RouteFor;
global using PublicHolidaysDisplayTextFor = SolutionTemplate2.Shared.Statics.PublicHolidays.DisplayTextFor;
global using UsersDisplayTextFor = SolutionTemplate2.Shared.Statics.Users.DisplayTextFor;
global using WebUiDisplayTextFor = SolutionTemplate2.FrontEnd.WebUi.Common.Statics.DisplayTextFor;
